from copy import deepcopy

import pytest

from core.ddl.generator import DDLGeneratorConfig, generate_postgresql_ddl
from core.ddl.identifiers import PostgresIdentifierNormalizer
from core.ddl.models import DDLMode
from core.ddl.types import NumericEvidence, PostgresTypeMapper
from core.dimensional.validation import validate_dimensional_discovery
from core.profiling.models import SemanticRole
from core.quality.models import IdentifierConstraint
from core.star.engine import build_star_schema_contract
from core.star.models import SCDStrategyContract, SCDType
from core.star.validation import validate_star_schema_contract
from tests.golden_dimensional.test_golden_dimensional import proposal


def generated(name="ddl", *, scd2=False, constraints=None, transform=None, columns=None, data=None, grain=None):
    columns = columns or [("event_id", SemanticRole.IDENTIFIER),
                          ("customer_id", SemanticRole.IDENTIFIER),
                          ("amount", SemanticRole.MEASURE)]
    data = data or [["E1", "C1", 10], ["E2", "C2", 20]]
    grain = grain or ["event_id"]
    dataset, _, grain_definition, ids, dimensional_report = proposal(name, columns, data, grain)
    dimensional = validate_dimensional_discovery(dimensional_report,
        accepted_unresolved_fields=dimensional_report.unresolved_fields)
    report = build_star_schema_contract(dataset, grain_definition, dimensional, constraints or {})
    if transform: transform(report, ids)
    overrides = {}
    if scd2 and report.contract.dimension_tables:
        dim = report.contract.dimension_tables[0]
        overrides[dim.dimension_id] = SCDStrategyContract(
            dimension_id=dim.dimension_id, strategy=SCDType.TYPE_2,
            effective_from_field_plan="effective_from", effective_to_field_plan="effective_to",
            current_flag_plan="is_current", reason="Golden validated SCD2", requires_validation=False)
    validation = validate_star_schema_contract(report, scd_overrides=overrides)
    return dataset, ids, validation, generate_postgresql_ddl(validation)


def test_a_basic_star():
    _, _, _, (plan, artifact) = generated()
    assert "CREATE SCHEMA bi" in artifact.sql and plan.tables and artifact.validation_passed


def test_b_surrogate_key():
    _, _, _, (_, artifact) = generated("surrogate")
    assert "BIGINT GENERATED BY DEFAULT AS IDENTITY" in artifact.sql


def test_c_composite_business_key():
    def edit(report, ids):
        bk = report.contract.dimension_tables[0].business_key_fields
        bk.fields = [ids["customer_id"], ids["region_id"]]
        bk.uniqueness_expected = True
    columns = [("event_id", SemanticRole.IDENTIFIER), ("customer_id", SemanticRole.IDENTIFIER),
               ("region_id", SemanticRole.IDENTIFIER), ("amount", SemanticRole.MEASURE)]
    _, _, _, (_, artifact) = generated("composite", transform=edit, columns=columns,
                                       data=[["E1", "C1", "R1", 1]], grain=["event_id"])
    assert "UNIQUE (" in artifact.sql and ", " in artifact.sql.split("UNIQUE (")[1].split(")")[0]


def test_d_degenerate_dimension():
    cols = [("invoice_number", SemanticRole.IDENTIFIER), ("line_id", SemanticRole.IDENTIFIER),
            ("amount", SemanticRole.MEASURE)]
    _, _, _, (_, artifact) = generated("degenerate", columns=cols,
        data=[["I1", "1", 2], ["I1", "2", 3]], grain=["invoice_number", "line_id"])
    assert "invoice_number" in artifact.sql and "dim_invoice" not in artifact.sql


def test_e_role_playing_date():
    cols = [("event_id", SemanticRole.IDENTIFIER), ("order_date", SemanticRole.DATE),
            ("ship_date", SemanticRole.DATE), ("payment_date", SemanticRole.DATE)]
    _, _, _, (plan, _) = generated("roles", columns=cols,
        data=[["E1", "2026-01-01", "2026-01-02", "2026-01-03"]], grain=["event_id"])
    dims = [t for t in plan.tables if t.table_type == "DIMENSION"]
    assert len(dims) == 1 and len(plan.foreign_keys) == 3


def test_f_factless_fact():
    cols = [("event_id", SemanticRole.IDENTIFIER), ("customer_id", SemanticRole.IDENTIFIER)]
    _, _, _, (plan, _) = generated("factless", columns=cols, data=[["E1", "C1"]], grain=["event_id"])
    assert not [c for t in plan.tables for c in t.columns if c.role == "MEASURE"]


def test_g_multi_fact():
    dataset, _, grain_definition, _, report = proposal("multi_ddl", [
        ("event_a", SemanticRole.IDENTIFIER), ("event_b", SemanticRole.IDENTIFIER),
        ("customer_id", SemanticRole.IDENTIFIER), ("amount", SemanticRole.MEASURE)],
        [["A1", None, "C1", 2], [None, "B1", "C1", 3]], ["event_a", "event_b"],
        multi_groups=[["event_a"], ["event_b"]])
    dimensional = validate_dimensional_discovery(report, accepted_unresolved_fields=report.unresolved_fields)
    star = build_star_schema_contract(dataset, grain_definition, dimensional)
    plan, _ = generate_postgresql_ddl(validate_star_schema_contract(star))
    assert sum(t.table_type == "FACT" for t in plan.tables) == 2


def test_h_scd_type_2():
    _, _, _, (_, artifact) = generated("scd2", scd2=True)
    assert all(x in artifact.sql for x in ("effective_from", "effective_to", "is_current"))


def test_i_scd_unknown():
    _, _, _, (_, artifact) = generated("scdu")
    assert "effective_from" not in artifact.sql and any("SCD UNKNOWN" in w for w in artifact.warnings)


def test_j_bridge_only_when_validated():
    def edit(report, _):
        if report.contract.bridge_candidates: report.contract.bridge_candidates[0].requires_validation = False
    cols = [("event_id", SemanticRole.IDENTIFIER), ("person_id", SemanticRole.IDENTIFIER),
            ("group_id", SemanticRole.IDENTIFIER)]
    _, _, _, (plan, _) = generated("bridge", transform=edit, columns=cols,
        data=[["E1", "P1", "G1"], ["E2", "P1", "G2"], ["E3", "P2", "G1"], ["E4", "P2", "G2"]],
        grain=["event_id"])
    _, _, _, (unvalidated, _) = generated("bridge_unvalidated", columns=cols,
        data=[["E1", "P1", "G1"], ["E2", "P1", "G2"], ["E3", "P2", "G1"], ["E4", "P2", "G2"]],
        grain=["event_id"])
    assert sum(t.table_type == "BRIDGE" for t in plan.tables) == 1
    assert not any(t.table_type == "BRIDGE" for t in unvalidated.tables)


def test_k_nullability():
    _, _, _, (plan, _) = generated("nullable")
    assert any(c.nullable for t in plan.tables for c in t.columns)


def test_l_numeric_precision():
    mapped, meta, _ = PostgresTypeMapper(numeric_precision_margin=2).map(
        __import__("core.star.models", fromlist=["LogicalDataType"]).LogicalDataType.DECIMAL,
        numeric_evidence=NumericEvidence(12, 2))
    assert mapped == "NUMERIC(14,2)" and meta["selected_precision"] >= meta["observed_precision"]


def test_m_text_mapping():
    _, _, _, (_, artifact) = generated("text")
    assert "TEXT" in artifact.sql and "VARCHAR(255)" not in artifact.sql


def test_n_reserved_word():
    assert PostgresIdentifierNormalizer.canonical("select") == "select_"


def test_o_identifier_63_bytes():
    value = PostgresIdentifierNormalizer.canonical("á" * 100)
    assert len(value.encode()) <= 63 and value == PostgresIdentifierNormalizer.canonical("á" * 100)


def test_p_name_collision():
    normalizer = PostgresIdentifierNormalizer()
    assert [normalizer.normalize(x) for x in ("customer", "Customer", "customer!")] == ["customer", "customer_2", "customer_3"]


def test_q_fk_index():
    _, _, _, (plan, _) = generated("fkindex")
    assert plan.foreign_keys and plan.indexes


def test_r_technical_key_exclusion():
    cols = [("source_row_id", SemanticRole.IDENTIFIER), ("event_id", SemanticRole.IDENTIFIER),
            ("customer_id", SemanticRole.IDENTIFIER)]
    _, _, _, (_, artifact) = generated("technical", columns=cols,
                                       data=[["S1", "E1", "C1"]], grain=["event_id"])
    assert "source_row_id" not in artifact.sql


def test_s_aggregation_risk():
    cols = [("invoice", SemanticRole.IDENTIFIER), ("item", SemanticRole.IDENTIFIER),
            ("invoice_total", SemanticRole.MEASURE)]
    _, _, _, (plan, artifact) = generated("risk", columns=cols,
        data=[["I1", "1", 100], ["I1", "2", 100]], grain=["invoice", "item"])
    assert any(c.metadata.get("aggregation_risk") for t in plan.tables for c in t.columns) and "invoice_total" in artifact.sql


def test_t_determinism():
    _, _, validation, (_, first) = generated("determinism")
    _, second = generate_postgresql_ddl(validation)
    assert first.sql == second.sql and first.fingerprint == second.fingerprint


def test_u_no_destructive_sql_and_safe_mode():
    _, _, validation, _ = generated("safe")
    _, artifact = generate_postgresql_ddl(validation, config=DDLGeneratorConfig(ddl_mode=DDLMode.SAFE_CREATE))
    assert "IF NOT EXISTS" in artifact.sql and not any(x in artifact.sql.upper() for x in ("DROP ", "TRUNCATE ", "DELETE ", "ALTER "))


def test_readiness_gate_blocks_not_ready():
    _, _, validation, _ = generated("blocked")
    validation.readiness = __import__("core.star.models", fromlist=["ReadinessStatus"]).ReadinessStatus.NOT_READY
    with pytest.raises(ValueError, match="BLOCKED"):
        generate_postgresql_ddl(validation)
