"""Repository contract: the persistent source of truth for analyses."""

from typing import Protocol

from core.persistence.models import AnalysisHistoryItem, AnalysisRecord, AnalysisResumeResult, SourceDocument
from core.profiling.models import WorkbookProfile
from core.semantic.models import SemanticKnowledgeRecord, SemanticValidationReport
from core.quality.models import DataQualityReport
from core.prepared.models import (PreparedDataset, PreparedDatasetArtifact,
                                  PreparedGenerationStatus)
from core.persistence.models import (
    GrainDefinitionRecord, GrainDiscoveryRecord, PreparedDatasetRecord,
)
from core.grain.models import GrainDefinition, GrainDiscoveryReport
from core.dimensional.models import DimensionalDiscoveryReport, ValidatedDimensionalDiscovery
from core.persistence.models import DimensionalDiscoveryRecord, ValidatedDimensionalRecord
from core.star.models import StarSchemaContract, StarSchemaContractReport, ValidatedStarSchemaContract
from core.persistence.models import StarSchemaContractRecord, ValidatedStarSchemaRecord
from core.ddl.models import PhysicalSchemaPlan, PostgreSQLDDLArtifact
from core.persistence.models import PhysicalSchemaPlanRecord, PostgreSQLDDLArtifactRecord
from core.etl.models import DimensionalETLPlan, ValidatedDimensionalETLPlan
from core.persistence.models import DimensionalETLPlanRecord, ValidatedDimensionalETLPlanRecord
from core.transformation.models import DimensionalTransformationRun
from core.persistence.models import DimensionalTransformationRunRecord
from core.database_dry_run.models import DatabaseDryRun
from core.persistence.models import DatabaseDryRunRecord


class AnalysisRepository(Protocol):
    def register_document(self, content: bytes, original_name: str) -> SourceDocument: ...
    def find_document(self, content: bytes) -> SourceDocument | None: ...
    def list_analyses(self, source_document_id: str) -> list[AnalysisRecord]: ...
    def list_analyses_for_document(self, source_document_id: str) -> list[AnalysisHistoryItem]: ...
    def resume_analysis(self, analysis_id: str, source_document_id: str | None = None) -> AnalysisResumeResult: ...
    def create_analysis(self, source_document_id: str, profile: WorkbookProfile) -> AnalysisRecord: ...
    def get_analysis(self, analysis_id: str) -> AnalysisRecord | None: ...
    def get_answers(self, analysis_id: str) -> dict[str, dict[str, str | None]]: ...
    def list_semantic_knowledge(self, source_document_id: str, *, history: bool = False) -> list[SemanticKnowledgeRecord]: ...
    def save_answer(self, analysis_id: str, question_id: str, answer: str, custom_answer: str | None = None) -> AnalysisRecord: ...
    def save_report(self, report: SemanticValidationReport) -> AnalysisRecord: ...
    def get_quality_report(self, analysis_id: str) -> DataQualityReport | None: ...
    def list_quality_reports(self, analysis_id: str) -> list[DataQualityReport]: ...
    def save_quality_report(self, report: DataQualityReport) -> DataQualityReport: ...
    def next_prepared_version(self, analysis_id: str) -> int: ...
    def save_prepared_dataset(self, dataset: PreparedDataset) -> PreparedDatasetRecord: ...
    def save_prepared_artifact(self, artifact: PreparedDatasetArtifact) -> PreparedDatasetRecord: ...
    def get_prepared_artifact(self, prepared_dataset_id: str) -> PreparedDatasetArtifact | None: ...
    def update_prepared_generation(self, prepared_dataset_id: str, analysis_id: str,
                                   version: int, status: PreparedGenerationStatus,
                                   stage: str, reason: str | None = None) -> None: ...
    def mark_stale_prepared_generations_interrupted(self) -> int: ...
    def list_prepared_datasets(self, analysis_id: str) -> list[PreparedDatasetRecord]: ...
    def next_grain_report_version(self, prepared_dataset_id: str) -> int: ...
    def save_grain_discovery_report(self, report: GrainDiscoveryReport) -> GrainDiscoveryRecord: ...
    def list_grain_discovery_reports(self, prepared_dataset_id: str) -> list[GrainDiscoveryRecord]: ...
    def next_grain_definition_version(self, prepared_dataset_id: str) -> int: ...
    def save_grain_definition(self, definition: GrainDefinition) -> GrainDefinitionRecord: ...
    def get_effective_grain(self, prepared_dataset_id: str) -> GrainDefinition | None: ...
    def next_dimensional_report_version(self, prepared_dataset_id: str) -> int: ...
    def save_dimensional_discovery_report(self, report: DimensionalDiscoveryReport) -> DimensionalDiscoveryRecord: ...
    def list_dimensional_discovery_reports(self, prepared_dataset_id: str) -> list[DimensionalDiscoveryRecord]: ...
    def next_dimensional_validation_version(self, prepared_dataset_id: str) -> int: ...
    def save_validated_dimensional_discovery(self, validation: ValidatedDimensionalDiscovery) -> ValidatedDimensionalRecord: ...
    def get_effective_dimensional_discovery(self, prepared_dataset_id: str) -> ValidatedDimensionalDiscovery | None: ...
    def next_star_schema_report_version(self, prepared_dataset_id: str) -> int: ...
    def save_star_schema_contract_report(self, report: StarSchemaContractReport) -> StarSchemaContractRecord: ...
    def list_star_schema_contract_reports(self, prepared_dataset_id: str) -> list[StarSchemaContractRecord]: ...
    def next_star_schema_validation_version(self, prepared_dataset_id: str) -> int: ...
    def save_validated_star_schema_contract(self, validation: ValidatedStarSchemaContract) -> ValidatedStarSchemaRecord: ...
    def get_effective_star_schema_contract(self, prepared_dataset_id: str) -> StarSchemaContract | None: ...
    def next_ddl_version(self, star_schema_contract_id: str) -> int: ...
    def save_physical_schema_plan(self, plan: PhysicalSchemaPlan) -> PhysicalSchemaPlanRecord: ...
    def save_postgresql_ddl_artifact(self, artifact: PostgreSQLDDLArtifact) -> PostgreSQLDDLArtifactRecord: ...
    def get_postgresql_ddl_artifact(self, ddl_artifact_id: str) -> PostgreSQLDDLArtifact | None: ...
    def get_effective_physical_schema(self, prepared_dataset_id: str) -> PhysicalSchemaPlan | None: ...
    def next_etl_plan_version(self, physical_schema_plan_id: str) -> int: ...
    def save_dimensional_etl_plan(self, plan: DimensionalETLPlan) -> DimensionalETLPlanRecord: ...
    def get_dimensional_etl_plan(self, etl_plan_id: str) -> DimensionalETLPlan | None: ...
    def next_etl_validation_version(self, prepared_dataset_id: str) -> int: ...
    def save_validated_dimensional_etl_plan(self, validation: ValidatedDimensionalETLPlan) -> ValidatedDimensionalETLPlanRecord: ...
    def get_effective_dimensional_etl_plan(self, prepared_dataset_id: str) -> DimensionalETLPlan | None: ...
    def save_dimensional_transformation_run(self, run: DimensionalTransformationRun) -> DimensionalTransformationRunRecord: ...
    def get_dimensional_transformation_run(self, run_id: str) -> DimensionalTransformationRun | None: ...
    def save_database_dry_run(self, run: DatabaseDryRun) -> DatabaseDryRunRecord: ...
    def get_database_dry_run(self, dry_run_id: str) -> DatabaseDryRun | None: ...
